version: 2
jobs:
  build:
    docker:
      - image: node:alpine
    working_directory: ~/mv-lite
    steps:
      - checkout
      - run:
          name: Install dependancies
          command: npm install
      - run:
          name: Run tests
          command: npm test
